server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: item-service
          uri: http://item-service:8081
          predicates:
            - Path=/items/**

        - id: order-service
          uri: http://order-service:8082
          predicates:
            - Path=/orders/**

        - id: payment-service
          uri: http://payment-services:8083
          predicates:
            - Path=/payments/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway